services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///./history.db
    volumes:
      - ./database.db:/app/database.db
    depends_on:
      - redis

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"